version: "3.8"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"                      # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=1
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${LOCALSTACK_WEB_UI_PORT:-8081}
      - LAMBDA_EXECUTOR=local
      - DOCKER_SOCK=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - S3_SKIP_SIGNATURE_VALIDATION=0 # validate presigned request
    volumes:
      - './localstack:/var/lib/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"  # docker time synchronized
